# Generated by Django 4.2.2 on 2023-07-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField()),
                ("phone_nr", models.CharField(max_length=9)),
                ("country", models.CharField(default="Polska", max_length=60)),
                ("city", models.CharField(max_length=45)),
                ("postal_code", models.CharField(max_length=5)),
                ("street", models.CharField(max_length=75)),
                ("house_nr", models.CharField(max_length=10)),
                ("flat_nr", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=60)),
                ("phone_nr", models.CharField(max_length=9)),
                ("email", models.CharField(max_length=60)),
                ("country", models.CharField(default="Polska", max_length=60)),
                ("city", models.CharField(max_length=45)),
                ("postal_code", models.CharField(max_length=5)),
                ("street", models.CharField(max_length=75)),
                ("house_nr", models.CharField(max_length=10)),
                ("flat_nr", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Furniture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("availability", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("description", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Producers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("delivery_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_weight", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.paymentmethods",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.paymentstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cost_with_delivery",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity_ordered", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.customers",
                    ),
                ),
                (
                    "delivery_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.deliverydetails",
                    ),
                ),
                (
                    "order_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.orderstatus",
                    ),
                ),
                (
                    "ordered_items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.furniture",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.payments",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store.suppliers",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="furniture",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_store.producers"
            ),
        ),
    ]
