# Generated by Django 4.2.2 on 2023-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store", "0002_customers_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="phone_nr",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="customers",
            name="postal_code",
            field=models.CharField(max_length=6),
        ),
    ]
