# Generated by Django 4.2.2 on 2023-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store", "0003_alter_customers_phone_nr_alter_customers_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="flat_nr",
            field=models.IntegerField(null=True),
        ),
    ]
