# Generated by Django 4.2.2 on 2023-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store", "0005_alter_customers_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="flat_nr",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
