# Generated by Django 4.2.2 on 2023-07-10 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_store", "0006_alter_customers_flat_nr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="city",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="country",
            field=models.CharField(default="Polska", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="house_nr",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="phone_nr",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="postal_code",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="street",
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
